image:
  repository: ghcr.io/berriai/litellm
  tag: main-latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 4000

env:
  STORE_MODEL_IN_DB: "False"

masterKey: sk-litellm-master

modelList: []
