fullnameOverride: ollama-judge

image:
  repository: 923373850235.dkr.ecr.ap-south-1.amazonaws.com/mirror/ollama
  tag: "0.23.2"

ollama:
  gpu:
    enabled: false
  models:
    - llama3.1:8b

nodeSelector:
  role: system

resources:
  requests:
    cpu: 2000m
    memory: 6Gi
  limits:
    cpu: 4000m
    memory: 8Gi
