fullnameOverride: ollama-embed

ollama:
  gpu:
    enabled: false
  models:
    - nomic-embed-text

nodeSelector:
  role: system

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 3Gi
