replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.2.5"
  pullPolicy: IfNotPresent

nodeSelector: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 2Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: alb
  annotations: {}
  hostname: auth.firm.internal

env:
  KC_FEATURES: "ciba,par,dpop"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_DB: postgres
  KC_DB_URL: "jdbc:postgresql://keycloak-postgresql:5432/keycloak"

adminUser: admin
adminPassword: "changeme-set-via-vault"

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16.9-alpine3.21"
    pullPolicy: IfNotPresent
  database: keycloak
  username: keycloak
  password: "changeme-set-via-vault"
  storage: 8Gi
  storageClass: gp2-csi
  nodeSelector: {}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
