global:
  name: consul
  datacenter: ap-south-1
  image: "923373850235.dkr.ecr.ap-south-1.amazonaws.com/mirror/consul:1.22.7"
  tls:
    enabled: false
  acls:
    manageSystemACLs: true

server:
  replicas: 3
  nodeSelector: "role: system"
  affinity: ""
  storage: 10Gi
  storageClass: gp2-csi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

client:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

connectInject:
  enabled: false   # using Istio for mTLS, not Consul Connect

ui:
  enabled: true
  service:
    type: ClusterIP

dns:
  enabled: true
