replicaCount: 1

nodeSelector:
  role: system

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 2Gi

adminUser: admin
adminPassword: "changeme-set-via-vault"

ingress:
  enabled: false

env:
  KC_FEATURES: "ciba,par,dpop"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_DB: postgres
  KC_DB_URL: "jdbc:postgresql://keycloak-postgresql:5432/keycloak"

postgresql:
  enabled: true
  image:
    repository: 923373850235.dkr.ecr.ap-south-1.amazonaws.com/mirror/postgres
    tag: "16.9-alpine3.21"
    pullPolicy: IfNotPresent
  database: keycloak
  username: keycloak
  password: "changeme-set-via-vault"
  storage: 8Gi
  storageClass: gp2-csi
  nodeSelector:
    role: system
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
