deploymentMode: SingleBinary

loki:
  auth_enabled: false

  image:
    registry: 923373850235.dkr.ecr.ap-south-1.amazonaws.com
    repository: mirror/loki
    tag: "3.6.7"

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

singleBinary:
  replicas: 1
  nodeSelector:
    role: observability
  persistence:
    enabled: true
    size: 20Gi
    storageClass: gp2-csi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Disable unused scalable components
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

minio:
  enabled: false
gateway:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false
