image:
  repository: ""
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

nodeSelector:
  role: application

service:
  type: ClusterIP
  port: 8000

serviceAccount:
  name: ciba-acp

env:
  KEYCLOAK_URL: "http://keycloak.infra.svc.cluster.local"
  KEYCLOAK_REALM: "firm-internal"
  SNS_TOPIC_ARN: ""
  AWS_REGION: "us-east-1"
  LOG_LEVEL: "INFO"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
